// Diffs openImage against Go's OpenImage over a corpus of malformed, truncated
// and randomly-mutated PE files. Proves the parser agrees with debug/pe on
// adversarial input, and that it terminates on all of it.

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { openImage } from '../src/core/image.js';

const casesDir = process.argv[2] ?? '/tmp/ucpfuzz/cases';
const truthPath = process.argv[3] ?? '/tmp/ucpfuzz/go-fuzz-truth.json';

// These inputs are generated by a Go run, not committed, and the defaults live
// in /tmp so they do not survive a reboot. Say so instead of dying on a stack
// trace from readFileSync.
for (const [label, path] of [['case directory', casesDir], ['Go baseline', truthPath]]) {
  if (!existsSync(path)) {
    console.error(`fuzz-diff: ${label} not found: ${path}`);
    console.error('Generate it first (requires a Go toolchain):');
    console.error('  ./verification/gen-go-baseline.sh');
    console.error('or pass explicit paths: node verification/fuzz-diff.mjs <casesDir> <goTruth.json>');
    process.exit(2);
  }
}

const truth = new Map(
  JSON.parse(readFileSync(truthPath, 'utf8')).map((r) => [r.name, r]),
);

const diffs = [];
let checked = 0;
let slowest = { name: '', ms: 0 };

for (const name of readdirSync(casesDir).sort()) {
  const expected = truth.get(name);
  if (expected === undefined) continue;
  const p = join(casesDir, name);

  const started = process.hrtime.bigint();
  const actual = { name, err: '', panic: '', base: 0, ptrSize: 0, nSec: 0, nPdata: 0 };
  try {
    const img = openImage(p);
    actual.base = img.base;
    actual.ptrSize = img.ptrSize;
    actual.nSec = img.sections.length;
    actual.nPdata = img.pdata.length;
  } catch (err) {
    if (err instanceof RangeError) actual.panic = err.message;
    else actual.err = err.message;
  }
  const ms = Number(process.hrtime.bigint() - started) / 1e6;
  if (ms > slowest.ms) slowest = { name, ms };

  actual.err = actual.err.split(p).join('<F>');
  checked++;

  for (const k of ['err', 'panic', 'base', 'ptrSize', 'nSec', 'nPdata']) {
    if ((expected[k] ?? (typeof actual[k] === 'string' ? '' : 0)) !== actual[k]) {
      diffs.push({ name, field: k, go: expected[k], js: actual[k] });
    }
  }
}

console.log(`checked ${checked} malformed-PE cases`);
console.log(`slowest case: ${slowest.name} (${slowest.ms.toFixed(1)} ms)`);
if (diffs.length === 0) {
  console.log('ZERO DIVERGENCES on malformed input');
} else {
  console.log(`${diffs.length} DIVERGENCE(S):`);
  for (const d of diffs.slice(0, 40)) {
    console.log(`  ${d.name}.${d.field}\n    go: ${JSON.stringify(d.go)}\n    js: ${JSON.stringify(d.js)}`);
  }
}
process.exit(diffs.length === 0 ? 0 : 1);
